server {
    listen 443 ssl http2;
    server_name dyn.example.com;

    ssl_certificate     /etc/letsencrypt/live/dyn.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dyn.example.com/privkey.pem;

    location / {
        proxy_pass http://unix:/run/kdyndns/kdyndns.sock:;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
